GET http://localhost:4000/api/user

###

POST http://localhost:4000/api/user
Content-Type: application/json

{
    "firstname": "olifant",
    "lastname": "cookie",
    "email": "kaka@jajaj",
    "password" : "blä",
}
