GET http://localhost:4000/api/user

###

POST http://localhost:4000/api/user
Content-Type: application/json

{
    "email": "hasish",
    "password" : "kebabaen",
    "isAdmin": false
}

###

PUT http://localhost:4000/api/user/62878473958fe43138be76b3
Content-Type: application/json 

{   
    "email": "admin",
    "password": "admin"
}

###

DELETE http://localhost:4000/api/user/62877ff16c2c5476a6b0911d